# -*- coding: utf-8 -*-
"""Prog for AI Assignment 03 decision_trees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rb0Z1HNG7trbDgtm94DMyUKAQqYB1o5L
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn import tree

print("Program Success")

# =========================================
# Load Dataset
# =========================================

input_file = "data_decision_trees.txt"

data = np.genfromtxt(input_file, delimiter=',', dtype=str)

X = data[:, :-1].astype(float)
y = data[:, -1]

# =========================================
# Encode Labels
# =========================================

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# =========================================
# Visualize Input Data
# =========================================

plt.figure(figsize=(8,6))

plt.scatter(
    X[:,0],
    X[:,1],
    c=y_encoded,
    s=40,
    edgecolors='black'
)

plt.xlabel("Age")
plt.ylabel("Income")
plt.title("Input Data")

plt.savefig("input_data.png")
plt.show()

# =========================================
# Prepare Features and Labels
# =========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=5
)

print("\nClasses:")
print(np.unique(y))

print("\nTraining Samples:", len(X_train))
print("Testing Samples:", len(X_test))

# =========================================
# Decision Tree Classifier
# =========================================

dt_classifier = DecisionTreeClassifier(
    max_depth=4,
    random_state=0
)

dt_classifier.fit(X_train, y_train)

# =========================================
# Training Dataset Decision Tree
# =========================================

plt.figure(figsize=(20,10))

tree.plot_tree(
    dt_classifier,
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title("Training Dataset Decision Tree")

plt.savefig("training_tree.png")

plt.show()

# =========================================
# Testing Dataset Decision Tree
# =========================================

plt.figure(figsize=(20,10))

tree.plot_tree(
    dt_classifier,
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title("Testing Dataset Decision Tree")

plt.savefig("testing_tree.png")

plt.show()

# =========================================
# Classifier Performance
# =========================================

y_train_pred = dt_classifier.predict(X_train)
y_test_pred = dt_classifier.predict(X_test)

print("\n")
print("#"*40)
print("Classifier performance on Training Dataset")
print("#"*40)

print(classification_report(y_train, y_train_pred))

print("\n")
print("#"*40)
print("Classifier performance on Test Dataset")
print("#"*40)

print(classification_report(y_test, y_test_pred))

# =========================================
# Accuracy
# =========================================

dt_train_acc = dt_classifier.score(X_train, y_train)
dt_test_acc = dt_classifier.score(X_test, y_test)

print("\nTraining Accuracy:", round(dt_train_acc*100,2), "%")
print("Testing Accuracy:", round(dt_test_acc*100,2), "%")

# =========================================
# Random Forest Classifier
# =========================================

rf_classifier = RandomForestClassifier(
    n_estimators=100,
    max_depth=4,
    random_state=0
)

rf_classifier.fit(X_train, y_train)

rf_acc = rf_classifier.score(X_test, y_test)

print("\nRandom Forest Accuracy:", round(rf_acc*100,2), "%")

# =========================================
# Feature Importance
# =========================================

feature_importance = rf_classifier.feature_importances_

feature_names = [
    "Feature1","Feature2","Feature3","Feature4",
    "Feature5","Feature6","Feature7","Feature8",
    "Feature9","Feature10","Feature11","Feature12",
    "Feature13","Feature14"
]

indices = np.argsort(feature_importance)

plt.figure(figsize=(10,6))

plt.title("Feature Importance using Random Forest")

plt.bar(
    range(len(indices)),
    feature_importance[indices]
)

plt.xticks(
    range(len(indices)),
    [feature_names[i] for i in indices],
    rotation=45
)

plt.tight_layout()

plt.savefig("feature_importance.png")

plt.show()

# =========================================
# Extra Trees Classifier
# =========================================

extra_classifier = ExtraTreesClassifier(
    n_estimators=100,
    random_state=0
)

extra_classifier.fit(X_train, y_train)

extra_acc = extra_classifier.score(X_test, y_test)

# =========================================
# Balanced Random Forest
# =========================================

sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

balanced_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=0
)

balanced_rf.fit(
    X_train,
    y_train,
    sample_weight=sample_weights
)

balanced_acc = balanced_rf.score(X_test, y_test)

# =========================================
# Model Comparison Summary
# =========================================

models = [
    "Decision Tree",
    "Random Forest",
    "Extra Trees",
    "Balanced RF"
]

accuracies = [
    dt_test_acc*100,
    rf_acc*100,
    extra_acc*100,
    balanced_acc*100
]

plt.figure(figsize=(8,6))

bars = plt.bar(models, accuracies)

plt.ylabel("Accuracy (%)")
plt.title("Model Comparison - Test Accuracy")

for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{height:.1f}%",
        ha='center'
    )

plt.savefig("model_comparison.png")

plt.show()

# =========================================
# Accuracy Table
# =========================================

comparison_df = pd.DataFrame({
    "Model": models,
    "Test Accuracy (%)": [round(a,2) for a in accuracies]
})

print("\n")
print(comparison_df)

print("\nAssignment Completed Successfully!")